export const workshops = [
  {
    id: "ws-ux-figma",
    title: "Designing Intuitive Interfaces with Figma",
    club: "Design Club",
    date: "2026-03-15T16:00:00",
    durationHours: 2,
    location: "Lab 3, Design Block",
    capacity: 30,
    registered: 18,
    topics: ["UI/UX", "Prototyping", "Figma"],
    level: "Beginner friendly",
  },
  {
    id: "ws-web-dev",
    title: "Full-stack Web Dev Crash Course",
    club: "Coding Club",
    date: "2026-03-20T14:00:00",
    durationHours: 3,
    location: "CS Seminar Hall",
    capacity: 80,
    registered: 72,
    topics: ["JavaScript", "APIs", "Databases"],
    level: "Intermediate",
  },
  {
    id: "ws-ml-intro",
    title: "Intro to Machine Learning with Python",
    club: "AI & ML Club",
    date: "2026-03-25T10:00:00",
    durationHours: 3,
    location: "ECE Auditorium",
    capacity: 60,
    registered: 44,
    topics: ["ML", "Python", "Scikit-learn"],
    level: "Beginner friendly",
  },
  {
    id: "ws-robotics",
    title: "Hands-on Robotics: Build Your First Bot",
    club: "Robotics Club",
    date: "2026-03-28T09:30:00",
    durationHours: 4,
    location: "Robotics Lab",
    capacity: 25,
    registered: 25,
    topics: ["Hardware", "Arduino", "Sensors"],
    level: "All levels",
  },
  {
    id: "ws-public-speaking",
    title: "Confident Public Speaking for Techies",
    club: "Literary & Debate Club",
    date: "2026-03-22T11:00:00",
    durationHours: 2,
    location: "Main Seminar Hall",
    capacity: 50,
    registered: 21,
    topics: ["Soft skills", "Communication"],
    level: "Beginner friendly",
  },
  {
    id: "ws-cloud",
    title: "Cloud Basics on AWS",
    club: "Cloud Club",
    date: "2026-04-02T15:00:00",
    durationHours: 2,
    location: "Lab 5, CS Block",
    capacity: 40,
    registered: 10,
    topics: ["Cloud", "AWS"],
    level: "Intermediate",
  },
];

